# Generated by Django 3.2 on 2021-04-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='id',
        ),
        migrations.AddField(
            model_name='record',
            name='address',
            field=models.CharField(default='something', max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
