# Generated by Django 3.2 on 2021-05-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='isTerminated',
            field=models.BooleanField(default=False),
        ),
    ]
